# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('schema_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('statecrea', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('schema_name', models.CharField(max_length=100)),
            ],
        ),
    ]
